### ISSUE TITLE
Unable to checkout repo in Windows

### ISSUE THREAD

**Issue by angryfred** [assaabloy-ppi/salt-channel-c#20]
Some files seem to have colon, see:

$ git clone https://github.com/assaabloy-ppi/salt-channel-c.git
Cloning into 'salt-channel-c'...
remote: Counting objects: 1461, done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 1461 (delta 36), reused 57 (delta 14)Receiving objects:  97% (141,8/14 pa61)ck-reused , 1.13645 MiB |2
Receiving objects: 100% (1461/1461), 1.63 MiB | 2.90 MiB/s, done.
Resolving deltas: 100% (868/868), done.
Checking connectivity... done.
error: unable to create file fuzz-tests/input/read_parse/id:000000,orig:0d1c61ca63d00128af439b3027ee0c6cabb9d45a_ (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000002,orig:22affbdd8030eda395621b9d18e9768c271ddc70 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000003,orig:270e7ebc33cb62d684e076c1455c8e2ed43b0574 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000004,orig:28fd925b81e714cda31fa6db8a22c7887a8e4ab9 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000005,orig:70740a1cfdd51de80a105aca82bd79643b85fa11 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000006,orig:9508e90548b0440a4a61e5743b76c1e309b23b7f (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000007,orig:a7bf7f7e9c548c07d7a0aa117490a90ec76961db (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000008,orig:ab05fe23af6fe844b87e347534a3ff268d392a44 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000009,orig:c2fc2cb80c8e459995fe9abfa0ab106f5f960f21 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000010,orig:cbac731bf614fec70cbb3e001d3605c0eb00d10d (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000026,orig:dbf6ebdd3d125476d708b48fa2635f65f077b15d (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000027,orig:f1a234b55f9cf5c75972df70b32170148f06c6ad (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000028,orig:f4cdfb3aecbc272f872043e9712f4f973163aff9 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000038,src:000005,op:flip1,pos:0 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000041,src:000009+000014,op:splice,rep:8 (Invalid argument)
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by sijohans** [comment]
Fixed in https://github.com/assaabloy-ppi/salt-channel-c/commit/8032b9e2ad04560cbeb0374a9048c964acece6c7

**Comment by aamathae** [comment]
Seems to still exist in branch crypto-api:
mathae@SESSTL292 MINGW64 /c/git/salt-channel-c (master)
$ git checkout crypto-api
error: unable to create file fuzz-tests/input/read_parse/id:000000,orig:0d1c61ca63d00128af439b3027ee0c6cabb9d45a_ (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000002,orig:22affbdd8030eda395621b9d18e9768c271ddc70 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000003,orig:270e7ebc33cb62d684e076c1455c8e2ed43b0574 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000004,orig:28fd925b81e714cda31fa6db8a22c7887a8e4ab9 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000005,orig:70740a1cfdd51de80a105aca82bd79643b85fa11 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000006,orig:9508e90548b0440a4a61e5743b76c1e309b23b7f (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000007,orig:a7bf7f7e9c548c07d7a0aa117490a90ec76961db (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000008,orig:ab05fe23af6fe844b87e347534a3ff268d392a44 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000009,orig:c2fc2cb80c8e459995fe9abfa0ab106f5f960f21 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000010,orig:cbac731bf614fec70cbb3e001d3605c0eb00d10d (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000026,orig:dbf6ebdd3d125476d708b48fa2635f65f077b15d (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000027,orig:f1a234b55f9cf5c75972df70b32170148f06c6ad (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000028,orig:f4cdfb3aecbc272f872043e9712f4f973163aff9 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000038,src:000005,op:flip1,pos:0 (Invalid argument)
error: unable to create file fuzz-tests/input/read_parse/id:000041,src:000009+000014,op:splice,rep:8 (Invalid argument)
D       fuzz-tests/input/read_parse/id:000000,orig:0d1c61ca63d00128af439b3027ee0c6cabb9d45a_
D       fuzz-tests/input/read_parse/id:000002,orig:22affbdd8030eda395621b9d18e9768c271ddc70
D       fuzz-tests/input/read_parse/id:000003,orig:270e7ebc33cb62d684e076c1455c8e2ed43b0574
D       fuzz-tests/input/read_parse/id:000004,orig:28fd925b81e714cda31fa6db8a22c7887a8e4ab9
D       fuzz-tests/input/read_parse/id:000005,orig:70740a1cfdd51de80a105aca82bd79643b85fa11
D       fuzz-tests/input/read_parse/id:000006,orig:9508e90548b0440a4a61e5743b76c1e309b23b7f
D       fuzz-tests/input/read_parse/id:000007,orig:a7bf7f7e9c548c07d7a0aa117490a90ec76961db
D       fuzz-tests/input/read_parse/id:000008,orig:ab05fe23af6fe844b87e347534a3ff268d392a44
D       fuzz-tests/input/read_parse/id:000009,orig:c2fc2cb80c8e459995fe9abfa0ab106f5f960f21
D       fuzz-tests/input/read_parse/id:000010,orig:cbac731bf614fec70cbb3e001d3605c0eb00d10d
D       fuzz-tests/input/read_parse/id:000026,orig:dbf6ebdd3d125476d708b48fa2635f65f077b15d
D       fuzz-tests/input/read_parse/id:000027,orig:f1a234b55f9cf5c75972df70b32170148f06c6ad
D       fuzz-tests/input/read_parse/id:000028,orig:f4cdfb3aecbc272f872043e9712f4f973163aff9
D       fuzz-tests/input/read_parse/id:000038,src:000005,op:flip1,pos:0
D       fuzz-tests/input/read_parse/id:000041,src:000009+000014,op:splice,rep:8
Switched to branch 'crypto-api'
Your branch is up-to-date with 'origin/crypto-api'.

**Comment by sijohans** [comment]
Fixed
